### ISSUE TITLE
Complex React Element

### ISSUE THREAD

**Issue by hipstersmoothie** [zenflow/sweetalert2-react-content#1]
I would really like to render a complex react element inside of sweet alert. Is there any way to do this with your current setup?

**Comment by zenflow** [comment]
You should be able to render *any* react element using this.. Is it not working?

Let me get a jsfiddle template set up for this

**Comment by zenflow** [comment]
@hipstersmoothie Care to share what you discovered?

**Comment by hipstersmoothie** [comment]
I think i was just using everything together wrong. Sorry for so many issues!

**Comment by zenflow** [comment]
@hipstersmoothie I like issues 😉
